
/**
 * Array of filter options used for filtering transactions by type.
 * Each option contains a `value` representing the filter type and a `label` for display purposes.
 *
 * @type {Array<Object>}
 * @property {string} value - The filter value used internally
 * @property {string} label - The display label for the filter option
 */
export const filterOptions = [
  { value: "all", label: "All" },
  { value: "sold-stock", label: "Stock-sold" },
  { value: "bought-stock", label: "Stock-bought" },
  { value: "deposite-cash", label: "Cash-deposite" },
  { value: "withdraw-cash", label: "Cash-withdraw" },
];

/**
 * The current date and timestamp in the format `YYYY-MM-DD HH:MM:SS.SSS`.
 * This value is generated by taking the current date and time and formatting it to exclude the time zone.
 *
 * @type {string}
 */
export const currentDateAndTimestamp = new Date()
  .toISOString()
  .slice(0, 23)
  .replace("T", " ");

/**
 * The IP address of the backend server used for API requests.
 * This constant can be switched between local development (`localHost`) or the AWS backend (`aws_backend`).
 *
 * @type {string}
 */
const localHost = "localhost:8080";
const aws_backend = "13.60.37.74:8080";

/**
 * The IP address of the backend server currently in use, set to the AWS backend by default.
 *
 * @type {string}
 */
export const SERVER_IP_ADDRESS = aws_backend;

